name: Provision or Deprovision Resource on AWS

on:
  push:
    branches:
      - main

jobs:
  provision:
    runs-on: ubuntu-latest

    steps:
      - name: Run Common Setup
        uses: ./.github/workflows/common-setup-workflow.yml
        with:
          region: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}


      - name: Provision Resources
        run: |
          echo $CDK_DEFAULT_REGION
          cdk bootstrap
          cdk deploy --require-approval never --all

  deprovision:
    runs-on: ubuntu-latest
    needs: [provision]

    steps:
      - name: Run Common Setup
        uses: ./.github/workflows/common-setup-workflow.yml
        with:
          region: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

      - name: Deprovision Resources
        run: |
          cdk bootstrap
          cdk destroy --all --force
